### ISSUE TITLE
Draft for infra-scraper integration

### ISSUE THREAD

**Issue by tomkukral** [Mirantis/kqueen#103]
Prepare draft/diagram explaining how to use [infra-scraper](https://github.com/cznewt/infra-scraper) in our API.

cc @cznewt

**Comment by cznewt** [comment]
Using infra scraper will give you several advantages:
- speed - you cannot do the async and think it will speed things up to point when it's fast
- history - you can keep historical data and do the change analysis
- visualizations - not just force-directed and hive
you just update config in ETCD on what you want to scrape

**Comment by tomkukral** [comment]
Closing as STALE.
