### ISSUE TITLE
add RelationField

### ISSUE THREAD

**Issue by tomkukral** [Mirantis/kqueen#28]
Add new field type: `RelationField` and it will be used to link other objects.

Serialized value: `ModelName:objectid`, for example `Cluster:203c50d6-3d09-4789-8b8b-1ecb00814436`

**Comment by pigmej** [comment]
Will you use multikey RW transactions in etcd to ensure that everything is consistent?

**Comment by tomkukral** [comment]
@pigmej our model is using `1:1` with allowed `1:None` so we need consistent writes only in a few special case which can be handled by two phase commits

**Comment by pigmej** [comment]
Yeah writes is the biggest problem there.
