### ISSUE TITLE
Documentation url on readthedocs doesn't show the latest version

### ISSUE THREAD

**Issue by ruzickap** [Mirantis/kqueen#283]
Hello.

It seems like "http://kqueen.readthedocs.io" is pointing to "http://kqueen.readthedocs.io/en/master/".

Actually the latest documentation is here: http://kqueen.readthedocs.io/en/latest/

Please check it and fix it on the readthedocs...

Thank you

**Comment by katyafervent** [comment]
I've updated settings on RTD, please verify that issue is fixed
